FROM node:alpine as builder

RUN mkdir -p /home/app/

WORKDIR /home/app/

COPY ./admin-frontend .
COPY ./.secrets/oauth-public.key ./.secrets/oauth-public.key
COPY .env.prod .env

RUN npm install pm2 -g

RUN npm i

RUN npm run build

EXPOSE 3000

CMD [ "pm2-runtime", "start","./.output/server/index.mjs"]
