FROM nginx:alpine as builder

COPY ./.secrets/student-attendance.internal.crt /etc/certs/student-attendance.internal/student-attendance.internal.crt
COPY ./.secrets/student-attendance.internal.key /etc/certs/student-attendance.internal/student-attendance.internal.key
COPY ./nginx/prod.conf /etc/nginx/nginx.conf

COPY ./api /var/www/html
COPY ./api/.env.production /var/www/html/.env