FROM python:alpine as builder

WORKDIR /home/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY . .

COPY .env.prod .env

RUN adduser -D appuser
RUN addgroup appuser tty
RUN addgroup appuser www-data
RUN addgroup appuser dialout

USER appuser

CMD [ "python", "server.py" ]
