FROM python:3-alpine as builder

WORKDIR /home/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY . .

COPY .env.prod .env

RUN adduser -D -g '' appuser
RUN addgroup -g tty -S appuser
RUN addgroup -g www-data -S appuser
RUN addgroup -g dialout -S appuser

USER appuser

CMD [ "python", "server.py" ]
